### ISSUE TITLE
Unable to connect to the remote server

### ISSUE THREAD

**Issue by kosnkow** [influxdata/influxdb-csharp#19]
When I try to insert oround 1M of points in packages every 10 points, sometimes (rather pretty offten) I got error "Unable to connect to the remote server" while server is running.

**Comment by nblumhardt** [comment]
Hi @kosnkow - thanks for raising an issue.

I haven't encountered this personally; it sounds like it could be a network or server-related issue, but if you uncover any clues as to where it's popping up, it'd be great to hear what you find.

Cheers!
Nick

**Comment by nblumhardt** [comment]
Closing until more information turns up. Thanks!
