### ISSUE TITLE
Improved error logging

### ISSUE THREAD

**Issue by optical** [influxdata/influxdb-csharp#22]
I'd like to log richer error events when something goes wrong when we're emitting points. Currently it looks like the only way to get notified of an error is via setting `CollectorLog.Out` to your own textwriter and logging those lines. There is no real way to associate an error with a point or instance of influxdb. This isn't ideal in complex applications which may have multiple collectors instantiated, etc. Additionally it'd be nice to have the Exception object, so that when we log via Serilog we can grab any further details off of the exception.

Do you have any thoughts on how we might improve the error reporting facilities? It seems like adding an Error event onto the `MetricsCollector` might be an option, or altering `Write` to return a `Task`. Not sure on what might be the best approach while maintaining backwards compatibility etc.

I haven't given this too much thought yet, hoping @nblumhardt might have some good ideas.

**Comment by nblumhardt** [comment]
Hey @optical!

+1 for this, I would need to get my head back into this space to be able to offer any worthwhile suggestions. It sounds like either changing/augmenting `CollectorLog` to expose more information on an error (`CollectorLog.Enable((msg, ex) => {...})` a-la Serilog?), or something similar on `MetricsCollector` would do it.

**Comment by optical** [comment]
Sorry for the delay in response; got a little sidetracked with other work. Anyhow.

I think changing `CollectorLog` as you suggested will probably be a good solution that will be easy for consumers to utilize, so I am happy with going with that over something baked into the `MetricsCollector` instance itself if you are. Are we happy with breaking the API and removing the existing method on `CollectorLog` from the start, given that this is still considered to be a beta package? 

On from that, I have played around with exposing an Async/Task based methods on the `IPointEmitter` interface which I believe would be feasible to implement and will provide some utility for consumers who want additional information about the lifecycle of a write event. Exposing Task means that consumers can log exceptions in a more natural `try { collector.Write(...); } catch { /*../* }` block. They could also get notified log when individual points are successfully emitted, retry them, etc, since there is a lot more context provided. The biggest issue I think here I think is opting to keep the existing non async methods, since they have subtly different behaviours. The current `Emit` method for example will is sometimes async, and other times not, but it will never raise an exception. Whereas the async version.will always return a Task which will represent the task for emitting that point - although with batching enabled the same task can be returned for multiple calls to EmitAsync (I think this is ok?). Retaining CollectorLog in this implementation is also tricky, but still possible. Ideally I think ripping out the non Task based methods entirely is actually the cleanest approach.

Does this task/async sound like something that would be worth considering? If so I am happy to push what I've got on a branch, looking at the code will probably demystify what I've written above.

**Comment by nblumhardt** [comment]
Hey Jared, thanks for the follow-up.

> Are we happy with breaking the API and removing the existing method on CollectorLog from the start, given that this is still considered to be a beta package?

Yes, I think so. 👍 

Switching to `Task` is an interesting discussion - on the one hand, it enables some scenarios, but on the other, it penalizes non-async code, which must then potentially deal with a compiler warning for a non-awaited return value (i.e. from `Write()`).

I've thought about this a lot in the context of Serilog, and concluded we'd be better off, over there, doing something like:

```csharp
Log.Information("Hello, World!");
await Log.FlushAsync();
```

I.e., separate the async part of the pipeline from the general write interface. This avoids issues with having to await `Log.InformationAsync()` (or `WriteAsync()` here), but still permits the caller to await the I/O.

Interleavings of course would make it imprecise (you are flushing, and thus waiting for, other writes that are batched up in the same payload), but in the few scenarios where a wait is required I think it'd probably be fine.

If you're keen to explore more, shall we open a separate thread? It'd be good to work through the improved internal error reporting in this one. Cheers!

**Comment by nblumhardt** [comment]
(I should have added - in both cases it'd also potentially avoid allocating a `Task` (or returning a chunky `ValueTask` struct, on every write call.)

**Comment by optical** [comment]
Cool - I'll go ahead and make the `CollectorLog` changes here as I think it'll provide an immediate improvement.

I'll spin up another issue here to discuss the possibilities of async/Task based methods once I've played with the code a bit more to see if it can be woven into what we've got already. I'll try get that this done this week.

**Comment by optical** [comment]
Closed via #26
