### ISSUE TITLE
Feature request: nanosecond precision

### ISSUE THREAD

**Issue by 1tgr** [influxdata/influxdb-csharp#34]
.NET DateTime is accurate only to the nearest 100 nanoseconds and the last two digits of the line protocol timestamp, as produced by the .NET client, will always be zero.

It would be good to be able to write data to nanosecond precision, even if it means using long instead of DateTime.

**Comment by gambrose** [comment]
@1tgr you can now use the `LineProtocolWriter` api to data using a long for the timestamp.


```
var writer = new LineProtocolWriter();
writer.Measurement("h2o_quality").Tag("location", "coyote_creek").Tag("randtag", "2").Field("index", 49f).Timestamp(1441922760);
var result = await client.SendAysnc(writer);
```

Is this sufficient? As nanosecond precision is more of an advanced use case I feel it makes sense to not complicate the `LineProtocolPoint` api.

The `LineProtocolWriter` api is more efficient which if you are writing points at the nanoscond level might be an advantage as I'm guessing there will be a lot of them?

**Comment by nblumhardt** [comment]
Closing due to staleness, anyone who's keen to push this forwards please feel free to jump. Thanks!
