### ISSUE TITLE
Feature proposal: LineProtocol writer to allow fewer allocations

### ISSUE THREAD

**Issue by gambrose** [influxdata/influxdb-csharp#35]
The current API requires allocating lots of memory to write points. Which is not great for performance if you are writing lots of points.
Each point needs allocate a class. These point classes store values and tags in dictionaries which means a lot more allocations as well as having to box and struct values as the values dictionary stores objects.

I propose we expose the functionality in `LineProtocolSyntax` e.g. `EscapeName` , `FormatTimespan` In a class that wrapped the TextWriter that is passed to the `Format` method of `LineProtocolPoint`.

This would allow clients the option store the point in a more efficient manor if they found the need to. But still fairly easily write correct line protocol.

Example

``` 
struct MyPoint
{
    public MyPoint(string host, float value, DateTime timestanp)
    {
        Host = host;
        Value = value;
        Timestanp = timestanp;
    }

    public string Host { get; }
    public float Value { get; }
    public DateTime Timestanp { get; }

    public void Format(LineProtocolWriter writer)
    {
        writer.Measument("my_point");
        writer.Tag("host", Host);
        writer.Value("value", Value);
        writer.Timestamp(Timestanp);
    }
}
```

Here we have a custom struct that we can use to store the data that can be written out to line protocol when needed.

I think this could be done in a way that is mostly backwards compatible with the current api.
If we define an interface that has a `Format(LineProtocolWriter writer)` method which `LineProtocolPoint` and `LineProtocolPayload` would implement. Change the client to accept the interface instead of the `LineProtocolPayload`.
This would also allow us to implement `LineProtocolWriter` to write UTF8 directly would avoid converting the whole payload to a string and then UTF8 encoding it.

`LineProtocolWriter` would keep track of what has been written so if you tried to write a value before a measurement name it would error. This would allow it to know when to insert line breaks.

The Client should also have a generic method for WriteAsync that would define the type of points being written which would be constrained to the point interface. This would allow passing in an array of point structs without boxing.

**Comment by gambrose** [comment]
Opened pull request #36 to hopefully better explain my thoughts.

I have also got a branch https://github.com/gambrose/influxdb-csharp/tree/precision which allows specifying the precision when writing points to influx. The documented guidance is to use the courses precision possible.

**Comment by nblumhardt** [comment]
Fantastic, thanks Graham. I'm currently a bit short on time to review a substantial PR on this, but will try to loop back to it as soon as I can. Hopefully others following along can dig in and provide some feedback in the meantime. Thanks again!

**Comment by tbolon** [comment]
Hi,

This PR is interesting. In our case, I am trying to build a custom Seq App which send some metrics to InfluxDB. Because we want to use some properties as tags and aggregate event count over time, we want to pay attention to allocations.

We can't use a ILineProtocolPayload implementation, since our struct does not contains all the required properties (only field values are stored in struct, tags are stored in the key structure and fixed tags are stored on the main class).

So, regarding your PR @gambrose, why not creating a more generic WriteAsync method which accepts a `LineProtocolWriter`, or perhaps even a `string` or an `HttpContent` ? If Collector library is aimed at performances, I think there should be a way for the developer to provide is own content built his own way.

I agree that it will certainly make the architecture less easy to understand. There will be 3 ways to send payload (from most guided/costly to most raw/optimized):

1. Use `WriteAsync(new LineProtocolPayload { new LineProcolPoint { Tags ... Fields ... } })`
2. Create `MyPoint : ILineProtocolPayload` and use `WriteAsync(new[] { point1, point2 })`
3. 💥 Write directly to `LineProtocolWriter` and use `WriteAsync(writer)`
4. 💥 Write directly to HttpContent ans use `WriteAsync(writer)`

Perhaps for better clarity we should create `SendAsync` overloads instead of `WriteAsync` for my suggestions ?

My actual code for reference:
```c#
namespace InfluxDB.LineProtocol.Client
{
    public class LineProtocolClient
    {
        public Task<LineProtocolWriteResult> WriteAsync(LineProtocolPayload payload, CancellationToken cancellationToken = default(CancellationToken))
        {
            return WriteAsync(new[] { payload }, cancellationToken);
        }

        public async Task<LineProtocolWriteResult> WriteAsync<TPayload>(IEnumerable<TPayload> payload, CancellationToken cancellationToken = default(CancellationToken), Precision precision = Precision.Nanoseconds) where TPayload : ILineProtocolPayload
        {
            if (payload == null)
            {
                throw new ArgumentNullException(nameof(payload));
            }

            LineProtocolWriter writer = new LineProtocolWriter(precision);

            foreach (var point in payload)
            {
                point.Format(writer);
            }

            return await WriteAsync(writer.ToString(), cancellationToken, precision);
        }

        public async Task<LineProtocolWriteResult> WriteAsync(string payload, CancellationToken cancellationToken = default(CancellationToken), Precision precision = Precision.Nanoseconds)
        {
            if (payload == null)
            {
                throw new ArgumentNullException(nameof(payload));
            }

            var content = new StringContent(payload, Encoding.UTF8);
            return await WriteAsync(content, cancellationToken, precision);
        }

        public async Task<LineProtocolWriteResult> WriteAsync(HttpContent payload, CancellationToken cancellationToken = default(CancellationToken), Precision precision = Precision.Nanoseconds)
        {
            if (payload == null)
            {
                throw new ArgumentNullException(nameof(payload));
            }

            var endpoint = $"write?db={Uri.EscapeDataString(_database)}";
            if (!string.IsNullOrEmpty(_username))
                endpoint += $"&u={Uri.EscapeDataString(_username)}&p={Uri.EscapeDataString(_password)}";

            switch (precision)
            {
                case Precision.Microseconds:
                    endpoint += "&precision=u";
                    break;
                case Precision.Milliseconds:
                    endpoint += "&precision=ms";
                    break;
                case Precision.Seconds:
                    endpoint += "&precision=s";
                    break;
                case Precision.Minutes:
                    endpoint += "&precision=m";
                    break;
                case Precision.Hours:
                    endpoint += "&precision=h";
                    break;
            }

            LineProtocolWriter writer = new LineProtocolWriter(precision);
            
            var response = await _httpClient.PostAsync(endpoint, payload, cancellationToken).ConfigureAwait(false);
            if (response.IsSuccessStatusCode)
                return new LineProtocolWriteResult(true, null);

            return new LineProtocolWriteResult(false, $"{response.StatusCode} {response.ReasonPhrase}");
        }
    }
}

```

**Comment by gambrose** [comment]
@tbolon 

How about exposing the private `CreateWriter` and the `WriteAsync` overload with a `LineProtocolWriter`. But rename the `WriteAsync`:`LineProtocolWriter` overload to `SendAsync` as I agree it makes it clearer what is happening.

The idea you call `CreateWriter` with a precision write your points then call `SendAsync`.

This resolves the issue with specify the precision and by controlling the creation of the `LineProtocolWriter` it should allow us to optimise the `LineProtocolWriter` to allocate less strings say using [System.Text.Formatting](https://github.com/dotnet/corefxlab/wiki#systemtextformatting) in a not breaking way in the future.

That said I'm not sure I total understand your use case. If you are aggregating points then do you not have some sort of batching. In which case I would of thought it made sense to implement `ILineProtocolPayload` on the object representing you batch.
Creating and Sending a `LineProtocolWriter` makes more sense in say a streaming scenario where you want to keep every point but reduce the number of objects created.

**Comment by tbolon** [comment]
My batch is a combination of dictionary and structs. Initially I did not regroup all these data in their own class (after each send, I simply cleared my dictionary and preserve some arrays with static values).

But you are right, I could have implemented ILineProtocolPayload on my whole class and process with the Format method instead of creating a LineProtocolWriter by myself.

Perhaps for clarity, and overload for WriteAsync(...) which accepts only one ILineProtocolPayload (instead of an enum) could make this scenario more easy to discover.

**Comment by gambrose** [comment]
I have written a simple benchmark comparing the `LineProtocolPoint` and the alternative syntax using [BenchmarkDotNet](http://benchmarkdotnet.org/)
https://github.com/gambrose/influxdb-csharp/tree/benchmark

``` ini

BenchmarkDotNet=v0.10.0
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-6700HQ CPU 2.60GHz, ProcessorCount=8
Frequency=2531249 Hz, Resolution=395.0619 ns, Timer=TSC
Host Runtime=Clr 4.0.30319.42000, Arch=64-bit RELEASE [RyuJIT]
GC=Concurrent Workstation
JitModules=clrjit-v4.7.2102.0
Job Runtime(s):
	Clr 4.0.30319.42000, Arch=64-bit RELEASE [RyuJIT]

            Method |          Mean |     StdDev |        Median | Scaled | Scaled-StdDev |
------------------ |-------------- |----------- |-------------- |------- |-------------- |
 LineProtocolPoint | 1,273.1373 us | 10.7010 us | 1,273.8386 us |   1.00 |          0.00 |
      CustomStruct |   728.7339 us | 33.9457 us |   720.8616 us |   0.57 |          0.03 |
```

I also did a spike with allowing pre-escaping the names https://github.com/gambrose/influxdb-csharp/tree/escaped.

This slightly furthers the gap to make it over twice as fast.

``` ini

BenchmarkDotNet=v0.10.0
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-6700HQ CPU 2.60GHz, ProcessorCount=8
Frequency=2531249 Hz, Resolution=395.0619 ns, Timer=TSC
Host Runtime=Clr 4.0.30319.42000, Arch=64-bit RELEASE [RyuJIT]
GC=Concurrent Workstation
JitModules=clrjit-v4.7.2102.0
Job Runtime(s):
	Clr 4.0.30319.42000, Arch=64-bit RELEASE [RyuJIT]


            Method |          Mean |     StdDev |        Median | Scaled | Scaled-StdDev |
------------------ |-------------- |----------- |-------------- |------- |-------------- |
 LineProtocolPoint | 1,376.6753 us | 22.6148 us | 1,376.8607 us |   1.00 |          0.00 |
      CustomStruct |   590.0985 us | 13.5501 us |   590.5638 us |   0.43 |          0.01 |
```

@nblumhardt I appreciate you are short on time. I now have a few feature branches.
* [LineProtocolWriter](https://github.com/gambrose/influxdb-csharp/tree/protocol-writer)
* [Presision](https://github.com/gambrose/influxdb-csharp/tree/precision)
* [Benchmark](https://github.com/gambrose/influxdb-csharp/tree/benchmark)
* [Pre-escaping](https://github.com/gambrose/influxdb-csharp/tree/escaped)

 Would it be easier for you to have one big pull request with all these features combined or would it be easier to review and merge each one separately?

**Comment by nblumhardt** [comment]
Hi @gambrose,

Thanks for pushing ahead with this stuff!

I've had a think about it; smaller PRs will be better. Perhaps the logical order is - precision first, since it's additive and not hugely invasive. Then, the benchmark harness, since the others are perf related. Next, pre-escaping, since it's also pretty direct. Finally, and probably the largest in terms of discussion/turnaround, the writer changes (I think your API proposal is strong, keen to look at alternatives too, though).

How does that sound to you?

**Comment by gambrose** [comment]
@nblumhardt most of the features are based off writer changes.

* Precision is specified at the payload level, all points in a payload need to have the same precision as it is sent in the query string. The writer enables this as it gives a context to store the precision when writing the points in the batch. Without it it is hard to cleanly let the points which write the timestamp know which precision to use.

* Benchmark works best with things to compare. I had `LineProtocolPoint` vrs `LineProtocolWriter` and another benchmark for pre-escaped vrs strings. As they only really report relative performance rather than a more generic points/second like the influx go benchmarking tool I think it makes sense to only include this when we have a feature to benchmark.

* Pre-escaping is tied the the `LineProtocolWriter` api. I don't see an easy way to incorporate it into `LineProtocolPoint` and to be honest I think that is best as `LineProtocolPoint` is the best api for getting started and as such we should try and keep it simple. Plus the perf gain is marginal compared to not using `LineProtocolPoint`.

So I would prefer if we could land the `LineProtocolWriter` pr before these other features.

I propose that I work on simplifying the `LineProtocolWriter` pr and making the changes as small as possible.

I think removing `ILineProtocolPayload` interface would be a good start. The more I have thought about it, with respect to @tbolon comments, the more I think it just adds more complexity than it warrants. Better to keep the a clear separation between the quick and easy `LineProtocolPoint` api and the more advanced and low level `LineProtocolWriter` api.
I would like to instead add the `CreateWriter` then call `SendAsync` to the client for a separate advanced api.

I could just include the `LineProtocolWriter` with no changes to `LineProtocolPoint` to use it. This would de-risk the change as nothing is changed and the update to use `LineProtocolWriter` could be tracked in a separate pr.

If we include the update to `LineProtocolPoint` to use the `LineProtocolWriter` I can also add back in the `Format` method that takes a TextWriter to not make a breaking api change.

@nblumhardt let me know how you would like me to proceed.

**Comment by gambrose** [comment]
@nblumhardt  I've cut down the PR to just include the new `LineProtocolWriter` api. This makes is a lot smaller PR.
If this gets accepted then I can create other PRs to add the other features we suggested and perhaps change `LineProtocolPoint` over to use the writer implementation.

**Comment by nblumhardt** [comment]
Sounds like a plan, @gambrose ! I'll take a look now 👍

**Comment by tbolon** [comment]
I was on holidays 🌞 Great job here 👍 I agree with all the remarks, keep the pr as small a possible for now as it will still allow the api to make less allocations and can be released earlier.
