### ISSUE TITLE
Error Collector doesn't return useful information

### ISSUE THREAD

**Issue by bladefist** [influxdata/influxdb-csharp#37]
I had an error where I was submitting my 1,000,0001th tag value and Influx was returning a very descriptive error about why my data was failing.

But my `CollectorLog.RegisterErrorHandler((message, exception)` was returning "BadRequest", nothing else.  Had to man in the middle the request to figure out why it was failing.

Can you include the influxdb error into the message?

**Comment by nblumhardt** [comment]
Thanks for the note, @bladefist - sounds like it would be a great improvement. Any help with shaping up a solution welcome 👍
