### ISSUE TITLE
SocketException

### ISSUE THREAD

**Issue by manojmaity** [influxdata/influxdb-csharp#43]
Unable to connect to the remote server ---> 
System.Net.Sockets.SocketException:
 A connection attempt failed because the 
 connected party did not properly respond after a period of time, 
 or established connection failed because connected host has failed to 
 respond  xxx.xxx.xxx.xxx:8086.

This error occurs sometimes, unable to find any reason.
While connecting to influx at 8086, we are using HttpClient class with timeout of 30 min. At the influx db configuration we have specified, timeout to be max.

Any help shall be appreciated.

Thanks,
Manoj

**Comment by nblumhardt** [comment]
Sorry we weren't able to make any suggestions on this.
