### ISSUE TITLE
Add interface for mocking

### ISSUE THREAD

**Issue by jeroenwo** [influxdata/influxdb-csharp#44]
Hi,

One of my projects uses the LineProtocolClient. I am using Moq as a mocking framework and I am currently missing an interface so I can mock the injection of the LineProtocolClient.

Can I just clone the repository, add one and create a pull request? Or is there a reason that it doesn't exist yet?

**Comment by gambrose** [comment]
`LineProtocolClient` has a protected constructor that accepts a `HttpMessageHandler`. You can see an example of using this `MockLineProtocolClient` in the tests project.

**Comment by jeroenwo** [comment]
Thanks! Different than what I am used to, but it fits my purpose.. :)

**Comment by gambrose** [comment]
It is a little strange as that is there to allow unit testing the `LineProtocolClient` itself. While not exposing the `HttpMessageHandler` as a direct dependency.
If you feel that changes could be made to the library that make it easier to use then, by all means reopen this issue.

**Comment by jeroenwo** [comment]
In my case, I wanted to test if my logging implementation was called whenever an error occurred. Which was possible with your solution:
```csharp
[TestMethod]
public async Task Writer_ErrorOccurs_LoggerIsCalled()
{
	var mockLineProtocolClient = new MockLineProtocolClient("doesnotexist");
	var loggerMock = new Mock<ILogger>();

	mockLineProtocolClient.Handler.Expect($"{mockLineProtocolClient.BaseAddress}write?db=alsodoesnotexist")
		.Respond(HttpStatusCode.BadRequest, "application/json", "{\"error\":\"does not matter\"}");

	var writer = new InfluxDbMetricsWriter(mockLineProtocolClient, loggerMock.Object);

	await writer.WriteAsync(new List<Metric>(), DateTime.UtcNow);

	loggerMock.Verify(x => x.Error(It.IsAny<string>(), It.IsAny<string>()), Times.Once);
}
```
I thought it would have been easier with an interface, but writing it down leads to:
```csharp
[TestMethod]
public async Task Writer_ErrorOccurs_LoggerIsCalled()
{
	var lineProtocolClientMock = new Mock<ILineProtocolClient>();
	var lineProtocalWriteResult = new Mock<ILineProtocolWriteResult>();
	var loggerMock = new Mock<ILogger>();

	lineProtocolWriteResult
		.Setup(x => x.Success)
		.Returns(false);
	lineProtocolClientMock
		.Setup(x => x.WriteAsync(It.IsAny<LineProtocolPayload>()))
		.ReturnsAsync(lineProtocolWriteResult);

	var writer = new InfluxDbMetricsWriter(lineProtocolClientMock.Object, loggerMock.Object);

	await writer.WriteAsync(new List<Metric>(), DateTime.UtcNow);

	loggerMock.Verify(x => x.Error(It.IsAny<string>(), It.IsAny<string>()), Times.Once);
}
```
`ILineProtocolClient` wouldn't be a problem I guess, but `LineProtocolWriteResult` is a value type and leads to (at least) a performance penalty when adding an interface to it.

There isn't much to test for my writer, I see no other use case as of this moment. So I am fine with the `MockLineProtocolClient` solution: I can test, they are green, life is good.. :)
