### ISSUE TITLE
Not able to use https with LineProtocolClient

### ISSUE THREAD

**Issue by murugend** [influxdata/influxdb-csharp#54]
I'm trying to use the LineProtocolClient to read data from a queue and upload to an https enabled influxdb. The following lines describe how we use the LineProtocol interface.

```
_client = new LineProtocolClient(new Uri("https://10.25.192.6:8086"), database: "datatest", username: "user", password: "password");

var influxResult = await _client.WriteAsync(payload);
```
The second line here fails when the influxdb has https enabled, but works fine otherwise. 

![image](https://user-images.githubusercontent.com/20225583/38555568-f0684ef2-3cc6-11e8-93fd-a0c98e41802d.png)

We are currently using a self-signed certificate.  Is the self-signed certificate the issue, or am I missing something? Any help is much appreciated.

**Comment by nblumhardt** [comment]
Hi! Yes, this looks like your self-signed cert. You can "trust" the cert on the calling machine to work around this. HTH!

**Comment by murugend** [comment]
Thanks, we found a workaround.
