### ISSUE TITLE
Serilog.Metrics integration

### ISSUE THREAD

**Issue by psibernetic** [influxdata/influxdb-csharp#6]
Hey sir, I am excited to see some work on InfluxDB coming from you. Are there plans or a current method of integrating this with Serilog.Metrics as a sink for that information?

Thanks for your work!

**Comment by nblumhardt** [comment]
Hi Ovan! No current plans - the factoring in this project now (separate protocol implementation from metrics collection) means that it should be feasible to package up in a _Serilog.Sinks.InfluxDB_ implementation.

Figuring out how to map the loose schema of log data onto something nicer to view in InfluxDB is still a bit of a challenge, interesting to get some ideas together around this...

I see there's a Serilog -> Seq -> InfluxDB integration in https://github.com/andymac4182/Seq.App.InfluxDB - not sure how the mapping is done there though.

**Comment by nblumhardt** [comment]
Closing this for now, but please do get in touch if you have a shot at this! :-) Cheers!
