### ISSUE TITLE
Publish to NuGet

### ISSUE THREAD

**Issue by vladchilom** [influxdata/influxdb-csharp#79]
Any chance a new version can be published to NuGet?

The migration to .NET standard 2.0 and UDP support are still under the `1.1.1-dev-10109` NuGet package. Also, the max batch size parameter #59 was merged but has not been released -- this would be useful.

**Comment by farmerau** [comment]
@russorat sorry to explicitly tag you here-- but seeing that you're active (within the last 7 days on this repo) is there any chance publishing for this repo could get turned on?

This fix in particular would resolve an issue I'm experiencing in a number of applications.

**Comment by russorat** [comment]
@farmerau no problem. We have these published in NuGet: https://www.nuget.org/profiles/influxdata

I think that might close this issue?

**Comment by russorat** [comment]
Oh wait, my bad, looks like those are for the new client library. Let me find out if we can publish this one there too.

**Comment by farmerau** [comment]
Thanks for taking a look into this! =)

**Comment by bednar** [comment]
Hi @farmerau, @vladchilom 

new version of client is published into NuGet.

Regards

**Comment by farmerau** [comment]
Thank you!
